asegurahoy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("seguros.urls", namespace="seguros")),
]

seguros/urls.py
from django.urls import path
from seguros import views

app_name = "seguros"

urlpatterns = [
    path("", views.home, name="home"),
    path("terms/", views.terms, name="terms"),
    path("privacidad/", views.privacidad, name="privacidad"),
    path("form/", views.tipo_form, name="tipo-form"),
    path("guardar-seguro/", views.GuardarSeguro.as_view(), name="guardar-seguro"),
    path("guardar-account/", views.guardar_account, name="guardar-account"),
    path("success/", views.success, name="success"),
    path("get-modelos-by-marca/", views.GetModeloByMarca.as_view(), name="get-modelos-by-marca"),
    path("get-versiones-by-modelo/", views.GetVersionesByModelo.as_view(), name="get-versiones-by-modelo"),
]

seguros/forms.py
from django import forms
from seguros import models 
import datetime

class AccountForm(forms.ModelForm):
    cod_postal = forms.CharField(label="C. P.")
    medio_cotizacion = forms.CharField(label="¿En qué medio prefiere recibir su cotización?", widget=forms.RadioSelect(choices=[
        ("WP","WhatsApp"),
        ("LL","Llamado")
    ]))

    def __init__(self, *args, **kwargs):
        super(AccountForm, self).__init__(*args, **kwargs)
        self.initial["medio_cotizacion"] = "WP"

    class Meta:
        model = models.Account
        fields = "__all__"

class AccidentesSeguroForm(forms.ModelForm):
    personas = forms.IntegerField(label="Cant. Personas", min_value=1)
    periodo = forms.ChoiceField(choices=(
            ("1","1 mes"),
            ("2","2 meses"),
            ("3","3 meses"),
            ("4","4 meses"),
            ("5","5 meses"),
            ("6","6 meses"),
            ("+6","+6 meses"),
        ),
        initial="1"
    )

    class Meta:
        model = models.AccidentesSeguro
        fields = "__all__"

class AutoSeguroForm(forms.ModelForm):
    año = forms.ChoiceField(choices=[(x, str(x)) for x in range(2023, 1952, -1)])
    marca = forms.ChoiceField(choices=[("OTRO","OTRO")])
    modelo = forms.CharField(widget=forms.widgets.Select())
    version = forms.CharField(label="Versión", widget=forms.widgets.Select())
    uso = forms.ChoiceField(choices=[
        ("P","Particular"),
        ("C","Comercial"),
    ])
    gnc = forms.ChoiceField(choices=[("Si","Si"), ("No", "No")])
    cero_km = forms.ChoiceField(label="O KM", choices=[("Si","Si"), ("No", "No")])

    def __init__(self, *args, **kwargs):
        super(AutoSeguroForm, self).__init__(*args, **kwargs)
        self.fields['marca'].choices += [(x["marca"],x["marca"]) for x in models.AutoList.objects.all().values("marca").distinct()]
        self.fields['año'].widget.attrs['max'] = datetime.datetime.now().year
        self.initial['uso'] = 'P'
        self.initial["cero_km"] = "No"
        self.initial["gnc"] = "No"


    def clean_año(self):
        año = int(self.cleaned_data['año'])
        if año > datetime.datetime.now().year:
            raise forms.ValidationError("El año es invalido")
        return año
    
    def clean_gnc(self):
        field = self.cleaned_data['gnc']
        return field == "Si"
    
    def clean_cero_km(self):
        field = self.cleaned_data['cero_km']
        return field == "Si"

    class Meta:
        model = models.AutoSeguro
        fields = "__all__"

class MotoSeguroForm(forms.ModelForm):
    año = forms.ChoiceField(choices=[(x, str(x)) for x in range(2023, 1969, -1)])
    marca = forms.ChoiceField(choices=[("OTRO","OTRO")])
    modelo = forms.CharField(widget=forms.widgets.Select)
    version = forms.CharField(label="Versión", widget=forms.widgets.Select)
    uso = forms.ChoiceField(choices=[
        ("P","Particular"),
        ("C","Comercial"),
    ])
    cero_km = forms.ChoiceField(label="O KM", choices=[("Si","Si"), ("No", "No")])

    def __init__(self, *args, **kwargs):
        super(MotoSeguroForm, self).__init__(*args, **kwargs)
        self.fields['marca'].choices += [(x["marca"],x["marca"]) for x in models.MotoList.objects.all().values("marca").distinct()]
        self.fields['año'].widget.attrs['max'] = datetime.datetime.now().year
        self.initial['uso'] = 'P'
        self.initial["cero_km"] = "No"


    def clean_año(self):
        año = int(self.cleaned_data['año'])
        if año > datetime.datetime.now().year:
            raise forms.ValidationError("El año es invalido")
        return año
    
    def clean_cero_km(self):
        field = self.cleaned_data['cero_km']
        return field == "Si"

    class Meta:
        model = models.MotoSeguro
        fields = "__all__"

class HogarSeguroForm(forms.ModelForm):
    construccion = forms.CharField(label="Tipo de construcción")
    material_techo = forms.CharField(label="Material de Techo")
    m2 = forms.IntegerField(label="Superficie en M2")
    valor = forms.FloatField(label="Valor en pesos")
    rejas = forms.ChoiceField(label="¿Posee Rejas?", 
        choices=[("Si", "Si"), ("No", "No")], 
        initial="Si"
    )
    linderos = forms.ChoiceField(label="Linderos", 
        choices=(
            ("SB","Sin baldio"),
            ("BA","Baldio abandonado"),
            ("BM","Baldio con medianera"),
        ), 
        initial="SB"
    )
    tipo_bici = forms.ChoiceField(label="¿Agrega Bicicleta?", 
        choices=(
            ("NO", "No agrego bicicleta"),
            ("SI", "Si, dentro y fuera del domicilio"),
        ), 
        initial="NO"
    )
    marca_modelo_bici = forms.CharField(label="Marca y Modelo")
    valor_bici = forms.FloatField(label="Valor en pesos")

    class Meta:
        model = models.HogarSeguro
        fields = "__all__"

class ComercioSeguroForm(forms.ModelForm):
    descripcion = forms.CharField(label="Actividad Comercial")
    construccion = forms.CharField(label="Tipo de construcción")
    material_techo = forms.CharField(label="Material de Techo")
    m2 = forms.IntegerField(label="Superficie en M2")
    valor = forms.FloatField(label="Valor en pesos")
    rejas = forms.ChoiceField(label="¿Posee Rejas?", 
        choices=[("Si", "Si"), ("No", "No")], 
        initial="Si"
    )
    linderos = forms.ChoiceField(label="Linderos", 
        choices=(
            ("SB","Sin baldio"),
            ("BA","Baldio abandonado"),
            ("BM","Baldio con medianera"),
        ), 
        initial="SB"
    )

    class Meta:
        model = models.ComercioSeguro
        fields = "__all__"

class BiciSeguroForm(forms.ModelForm):
    marca_modelo = forms.CharField(label="Marca y Modelo")
    año = forms.ChoiceField(choices=[(x, str(x)) for x in range(2023, 2016, -1)])
    tipo = forms.ChoiceField(choices=(
        ("MB","Mountain Bike"),
        ("R","Rutera"),
        ("BMX","BMX"),
        ("P","Paseo"),
    ), initial="MB")
    valor = forms.FloatField(label="Valor en pesos",  min_value=0, initial=0)
    material = forms.ChoiceField(choices=(
        ("AC","Acero"),
        ("AL","Aluminio"),
        ("CA","Carbon"),
        ("TI","Titanio"),
    ), initial="AC")
    rodado = forms.ChoiceField(choices=[(x, str(x)) for x in range(29, 9, -1)])

    def __init__(self, *args, **kwargs):
        super(BiciSeguroForm, self).__init__(*args, **kwargs)
        self.fields['año'].widget.attrs['max'] = datetime.datetime.now().year

    def clean_año(self):
        año = int(self.cleaned_data['año'])
        if año > datetime.datetime.now().year:
            raise forms.ValidationError("El año es invalido")
        return año

    class Meta:
        model = models.BiciSeguro
        fields = "__all__"

class MonopatinSeguroForm(forms.ModelForm):
    año = forms.ChoiceField(choices=[(x, str(x)) for x in range(2023, 2016, -1)])
    marca_modelo = forms.CharField(label="Marca y Modelo")
    tipo = forms.ChoiceField(
        label="Tipo",
        choices=(
            ("B","Bateria"),
            ("E","Electrico"),
        ),
        initial="B"
    )
    valor = forms.FloatField(label="Valor en pesos", min_value=0, initial=0)

    def __init__(self, *args, **kwargs):
        super(MonopatinSeguroForm, self).__init__(*args, **kwargs)
        self.fields['año'].widget.attrs['max'] = datetime.datetime.now().year

    def clean_año(self):
        año = int(self.cleaned_data['año'])
        if año > datetime.datetime.now().year:
            raise forms.ValidationError("El año es invalido")
        return año

    class Meta:
        model = models.MonopatinSeguro
        fields = "__all__"

class CamionSeguroForm(forms.ModelForm):
    año = forms.ChoiceField(choices=[(x, str(x)) for x in range(2023, 1952, -1)])
    año_acoplado = forms.ChoiceField(choices=[(x, str(x)) for x in range(2023, 1952, -1)])
    marca = forms.ChoiceField(choices=[("OTRO","OTRO")])
    modelo = forms.CharField(widget=forms.widgets.Select)
    version = forms.CharField(label="Versión", widget=forms.widgets.Select)
    gnc = forms.ChoiceField(choices=[("Si","Si"), ("No", "No")], initial="No")
    cero_km = forms.ChoiceField(label="O KM", choices=[("Si","Si"), ("No", "No")], initial="No")
    acoplado = forms.ChoiceField(label="¿Agrega acoplado?", choices=[("Si","Si"), ("No", "No")])
    radio = forms.ChoiceField(choices=[
        ("U","Urbano"),
        ("N","Nacional"),
    ])
    marca_modelo_acoplado = forms.CharField(label="Marca y Modelo")
    año_acoplado = forms.ChoiceField(
        label="Año",
        choices=[(x, str(x)) for x in range(2023, 1952, -1)]
    )

    def __init__(self, *args, **kwargs):
        super(CamionSeguroForm, self).__init__(*args, **kwargs)
        self.fields['marca'].choices += [(x["marca"],x["marca"]) for x in models.CamionList.objects.all().values("marca").distinct()]
        self.fields['año'].widget.attrs['max'] = datetime.datetime.now().year
        self.fields['año_acoplado'].widget.attrs['max'] = datetime.datetime.now().year
        self.initial['acoplado'] ="No"


    def clean_año(self):
        año = int(self.cleaned_data['año'])
        if año > datetime.datetime.now().year:
            raise forms.ValidationError("El año es invalido")
        return año
    
    def clean_gnc(self):
        field = self.cleaned_data['gnc']
        return field == "Si"
    
    def clean_cero_km(self):
        field = self.cleaned_data['cero_km']
        return field == "Si"


    def clean_acoplado(self):
        field = self.cleaned_data['acoplado']
        return field == "Si"
    def clean_año_acoplado(self):
        año_acoplado = self.cleaned_data['año_acoplado']
        if año_acoplado > datetime.datetime.now().year:
            raise forms.ValidationError("El año es invalido")
        return año_acoplado

    class Meta:
        model = models.CamionSeguro
        fields = "__all__"

class FlotaSeguroForm(forms.ModelForm):
    class Meta:
        model = models.FlotaSeguro

seguros/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
import uuid
from seguros import forms
from seguros import models

from rest_framework.views import APIView
from rest_framework.response import Response

# Create your views here.

TIPO_FORM_MAP = {
    "auto": forms.AutoSeguroForm,
    "moto": forms.MotoSeguroForm,
    "accidentes": forms.AccidentesSeguroForm,
    "hogar": forms.HogarSeguroForm,
    "comercio": forms.ComercioSeguroForm,
    "bici": forms.BiciSeguroForm,
    "monopatin": forms.MonopatinSeguroForm,
    "camion": forms.CamionSeguroForm,
    "flota": forms.FlotaSeguroForm,
    "vida": forms.VidaSeguroForm,
    "praxis_medica": forms.PraxisMedicaSeguroForm,
    "caucion": forms.CaucionSeguroForm,
    "celular": None,
}

TIPO_MODEL_MAP = {
    "auto": models.AutoList,
    "moto": models.MotoList,
    "camion": models.CamionList,
}

def home(request):
    return redirect(reverse("seguros:tipo-form"))

def terms(request):
    return render(request, "terms.html", {"terms": models.Terms.objects.all().first()})

def privacidad(request):
    return render(request, "privacidad.html", {"privacidad": models.Privacidad.objects.all().first()})

def home(request):
    return redirect(reverse("seguros:tipo-form")+"?tipo=auto")

def tipo_form(request):
    context = {}
    tipo = request.GET.get("tipo", None)
    if not tipo or tipo not in list(TIPO_FORM_MAP.keys()):
        messages.error(request, "Tipo de seguro invalido")
        return redirect("/")

    if tipo == "bici":
        context["tipo"] = tipo
        context["account_form"] = forms.AccountForm
        context["bici_form"] = forms.BiciSeguroForm
        context["monopatin_form"] = forms.MonopatinSeguroForm
    elif tipo == "flota":
        context["tipo"] = tipo
        context["account_form"] = forms.AccountForm
        context["form"] = TIPO_FORM_MAP[tipo]
    else:
        context["tipo"] = tipo
        context["account_form"] = forms.AccountForm
        context["form"] = TIPO_FORM_MAP[tipo]
    return render(request, "seguros/form.html", context)


class GuardarSeguro(APIView):

    def get(self, request, *args, **kwargs):
        if models.UserSeguro.objects.filter(uuid=request.session["uuid"]).exists():
            return render(request, "seguros/account-form.html", {
                "tipo": request.session["tipo"],
                "account_form": forms.AccountForm(),
            })
        else:
            return redirect("/")

    def post(self, request, *args, **kwargs):
        tipo = request.GET.get("tipo", None)
        if not tipo or tipo not in list(TIPO_FORM_MAP.keys()):
            messages.error(request, "Tipo de seguro invalido")
            return redirect("/")

        request.session["tipo"] = tipo
        print(tipo)
        if tipo == "bici":
            tipo_bici = request.POST.get("tipo-bici")
            if tipo_bici in ["bici","monopatin"]:
                form = TIPO_FORM_MAP[tipo_bici]
                form = form(request.POST)
                if form.is_valid():
                    form.save()
            else:
                messages.error(request, "Tipo Bici/Monopatin invalido")
                return redirect("/")
        else:
            form = TIPO_FORM_MAP[tipo]
            print(request.POST)
            form = form(request.POST)
            if not form.is_valid():
                print(form.errors)
                messages.error(request, "Datos de seguro invalidos")
                return redirect("/")

            obj = form.save()
        
        myuuid = uuid.uuid4()
        request.session["uuid"] = str(myuuid)
        user_seguro = models.UserSeguro(
            tipo=tipo,
            uuid=myuuid,
            data_id=int(obj.pk),
            completed=False,
        )
        user_seguro.save()
        return render(request, "seguros/account-form.html", {
            "tipo": tipo,
            "account_form": forms.AccountForm(),
        })
        


def guardar_account(request):
    if request.method == "POST":
        acc_form = forms.AccountForm(request.POST)
        if not acc_form.is_valid():
            messages.error(request, "Datos de cuenta invalidos")
            return redirect("/")
        
        tipo = request.session["tipo"]
        myuuid = request.session["uuid"]
        user_seguro = models.UserSeguro.objects.filter(tipo=tipo, uuid=str(myuuid))
        if not user_seguro.exists():
            messages.error(request, "Datos de seguro no cargados")
            return redirect("/")

        user_seguro = user_seguro.first()
        account = acc_form.save()
        user_seguro.account = account
        user_seguro.completed = True
        user_seguro.save()
        messages.success(request, "Seguro Creado")
        return redirect("/success/?tipo="+str(tipo))

    return redirect("/")


def success(request):
    return render(request, "seguros/success-user.html", {
        "tipo": request.GET.get("tipo", "auto")
    })


class GetModeloByMarca(APIView):

    def get(self, request):
        marca = request.GET.get("marca")
        tipo = request.GET.get("tipo", None)
        if not tipo or tipo not in list(TIPO_FORM_MAP.keys()):
            messages.error(request, "Tipo de seguro invalido")
            return redirect("/")

        model = TIPO_MODEL_MAP[tipo]
        return Response(data={
            "data": model.objects.filter(marca=marca).values("modelo").distinct()
        }, status=200)


class GetVersionesByModelo(APIView):

    def get(self, request):
        modelo = request.GET.get("modelo")
        marca = request.GET.get("marca")
        tipo = request.GET.get("tipo", None)
        if not tipo or tipo not in list(TIPO_FORM_MAP.keys()):
            messages.error(request, "Tipo de seguro invalido")
            return redirect("/")

        model = TIPO_MODEL_MAP[tipo]
        return Response(data={
            "data": model.objects.filter(marca=marca, modelo=modelo).values("version").distinct()
        }, status=200)

seguros/templates/seguros/account-form.html
{% extends "index.html" %}
{% load static %}
{% load seguros_filters %}

{% block main %}
    <div 
        class="form active"
        id="form-{{tipo}}"
        >   
        <form tipo="{{tipo}}" id="account-form" method="POST" action="{% url 'seguros:guardar-account' %}">
            {% csrf_token %}
            <div class="form-container">
                {% for fm in account_form %}
                    <div class="form-elem">
                        <label>{{fm.label}}</label>
                        {{fm}}
                    </div>
                {% endfor %}
                <div class="form-button">
                    <button>Siguiente</button>
                </div>
            </div>
        </form>
        <div class="image-container">
            <div class="image-text">
                {{tipo|image_text_filter|safe}}
            </div>
            <div class="image">
                <img src="{% static 'publicidad/'|add:tipo|add:'.png' %}" alt="{{tipo}}">
            </div>
        </div>
    </div>
{% endblock %}

{% block js_scripts %}
<script src="{% static 'js/account-form.js' %}"></script>
{% endblock %}

seguros/templates/seguros/form.html
{% extends "index.html" %}
{% load static %}
{% load seguros_filters %}

{% block main %}
    <div 
        class="form active"
        id="form-{{tipo}}"
        >   
        <form tipo="{{tipo}}" id="data-form" method="POST" action="{% url 'seguros:guardar-seguro' %}?tipo={{tipo}}">
            {% csrf_token %}
            <div class="form-container">
                {% if tipo == "celular" %}
                <div class="celular-container">
                    <p style="padding-right: 20px;">¡El seguro mas elegido por la gente!</p>
                    <br>
                    <div class="text-primary">
                        CONTRATA TU PLAN DE PROTECCIÓN
                    </div>
                    <div class="tilde-list">
                        <div class="tilde">
                            <img src="{% static 'icons/tilde.svg' %}" alt="tilde">
                            <div>Contra Robo</div>
                        </div>
                        <div class="tilde">
                            <img src="{% static 'icons/tilde.svg' %}" alt="tilde">
                            <div>Contra Daño</div>
                        </div>
                        <div class="tilde">
                            <img src="{% static 'icons/tilde.svg' %}" alt="tilde">
                            <div>Pantalla Protegida</div>
                        </div>
                    </div>
                    <br>
                    <a  href="https://www.segurocell.com/?pid=817c99c4861918e518dca75d712983eb" 
                        class="bg-primary"
                        style="
                        cursor: pointer;
                        text-decoration: none;
                        "
                        >Cotizar
                    </a>
                </div>
                
                {% elif tipo == "bici" %}
                    <div class="form-elem">
                        <label>Tipo</label>
                        <select name="tipo-bici" id="bici-select">
                            <option value="bici">Bicicleta</option>
                            <option value="monopatin">Monopatin</option>
                        </select>
                    </div>
                    {% for fm in bici_form %}
                    <div class="form-elem bici-elem">
                        <label>{{fm.label}}</label>
                        {{fm}}
                    </div>
                    {% endfor %}

                    {% for fm in monopatin_form %}
                    <div class="form-elem monopatin-elem">
                        <label>{{fm.label}}</label>
                        {{fm}}
                    </div>
                    {% endfor %}
                        
                    <div class="form-button">
                        <button>Siguiente</button>
                    </div>
                    
                {% elif tipo == "flota" %}
                    {% for fm in form %}
                        <div class="form-elem cantidad-elem">
                            <label>{{fm.label}}</label>
                            {{fm}}
                        </div>
                    {% endfor %}
                    
                    <div class="form-button">
                        <button>Siguiente</button>
                    </div>
                {% else %}
                    {% for fm in form %}
                        <div class="form-elem">
                            <label>{{fm.label}}</label>
                            {{fm}}
                        </div>
                    {% endfor %}
                    <div class="form-button">
                        <button>Siguiente</button>
                    </div>
                {% endif %}
            </div>
            
        </form>
        <div class="image-container">
            <div class="image-text">
                {{tipo|image_text_filter|safe}}
            </div>
            <br>
            <div class="image">
                <img src="{% static 'publicidad/'|add:tipo|add:'.png' %}" alt="{{tipo}}">
            </div>
        </div>
        
    </div>
{% endblock %}

{% block js_scripts %}
<script src="{% static 'js/seguros-form.js' %}"></script>
{% if tipo == "auto" %}
<script src="{% static 'js/modelo-version.js' %}"></script>
{% elif tipo == "moto" %}
<script src="{% static 'js/modelo-version.js' %}"></script>
{% elif tipo == "camion" %}
<script src="{% static 'js/modelo-version.js' %}"></script>
{% endif %}

<script src="{% static 'js/'|add:tipo|add:'-form.js' %}"></script>
{% endblock %}

seguros/templates/seguros/success-user.html
{% extends "index.html" %}
{% load static %}
{% load seguros_filters %}

{% block css %}
<style>
    .success-user-container .form-container a {
        width: 130px;
        margin-left: calc(100% - 150px);
        padding: 5px 10px;
        font-size: 14px;
        border-radius: 15px;
        background-color: var(--primary);
        color: white;
        /* transform: translateY(-45px); */
        height: 33px;
        border: none;
    }
</style>
{% endblock %}

{% block main %}
    <div class="success-user-container">
        <div class="form">
            <form id="success-user">
                <div class="form-container"
                    style="
                    display: flex!important;
                    flex-direction: column;
                    align-items: center;
                    justify-content: start;
                    padding: 30px;
                    height: 100%;
                    ">
                    <h2 class="top-title">¡Gracias por contactarnos!</h2>
                    <p style="align-self: flex-start; margin-bottom: 20px;margin-top: 20px; margin-right: 30px;">En breve, un asesor se comunicará con usted.</p>
                    <a class="button" href="/">Finalizar</a>
                </div>
                
            </form>
            <div class="image-container">
                <div class="image-text">
                    {{tipo|image_text_filter|safe}}
                </div>
                <div class="image">
                    <img src="{% static 'publicidad/'|add:tipo|add:'.png' %}" alt="{{tipo}}">
                </div>
            </div>
        </div>
    </div>
{% endblock %}