asegurahoy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("seguros.urls", namespace="seguros")),
]

seguros/urls.py
from django.urls import path
from seguros import views

app_name = "seguros"

urlpatterns = [
    path("", views.home, name="home"),
    path("terms/", views.terms, name="terms"),
    path("privacidad/", views.privacidad, name="privacidad"),
    path("form/", views.tipo_form, name="tipo-form"),
    path("guardar-seguro/", views.GuardarSeguro.as_view(), name="guardar-seguro"),
    path("guardar-account/", views.guardar_account, name="guardar-account"),
    path("success/", views.success, name="success"),
    path("get-modelos-by-marca/", views.GetModeloByMarca.as_view(), name="get-modelos-by-marca"),
    path("get-versiones-by-modelo/", views.GetVersionesByModelo.as_view(), name="get-versiones-by-modelo"),
]

seguros/forms.py
from django import forms
from seguros import models 
import datetime

class AccountForm(forms.ModelForm):
    cod_postal = forms.CharField(label="C. P.")
    medio_cotizacion = forms.CharField(label="¿En qué medio prefiere recibir su cotización?", widget=forms.RadioSelect(choices=[
        ("WP","WhatsApp"),
        ("LL","Llamado")
    ]))

    def __init__(self, *args, **kwargs):
        super(AccountForm, self).__init__(*args, **kwargs)
        self.initial["medio_cotizacion"] = "WP"

    class Meta:
        model = models.Account
        fields = "__all__"

class AccidentesSeguroForm(forms.ModelForm):
    personas = forms.IntegerField(label="Cant. Personas", min_value=1)
    periodo = forms.ChoiceField(choices=(
            ("1","1 mes"),
            ("2","2 meses"),
            ("3","3 meses"),
            ("4","4 meses"),
            ("5","5 meses"),
            ("6","6 meses"),
            ("+6","+6 meses"),
        ),
        initial="1"
    )

    class Meta:
        model = models.AccidentesSeguro
        fields = "__all__"

class AutoSeguroForm(forms.ModelForm):
    año = forms.ChoiceField(choices=[(x, str(x)) for x in range(2023, 1952, -1)])
    marca = forms.ChoiceField(choices=[("OTRO","OTRO")])
    modelo = forms.CharField(widget=forms.widgets.Select())
    version = forms.CharField(label="Versión", widget=forms.widgets.Select())
    uso = forms.ChoiceField(choices=[
        ("P","Particular"),
        ("C","Comercial"),
    ])
    gnc = forms.ChoiceField(choices=[("Si","Si"), ("No", "No")])
    cero_km = forms.ChoiceField(label="O KM", choices=[("Si","Si"), ("No", "No")])

    def __init__(self, *args, **kwargs):
        super(AutoSeguroForm, self).__init__(*args, **kwargs)
        self.fields['marca'].choices += [(x["marca"],x["marca"]) for x in models.AutoList.objects.all().values("marca").distinct()]
        self.fields['año'].widget.attrs['max'] = datetime.datetime.now().year
        self.initial['uso'] = 'P'
        self.initial["cero_km"] = "No"
        self.initial["gnc"] = "No"


    def clean_año(self):
        año = int(self.cleaned_data['año'])
        if año > datetime.datetime.now().year:
            raise forms.ValidationError("El año es invalido")
        return año
    
    def clean_gnc(self):
        field = self.cleaned_data['gnc']
        return field == "Si"
    
    def clean_cero_km(self):
        field = self.cleaned_data['cero_km']
        return field == "Si"

    class Meta:
        model = models.AutoSeguro
        fields = "__all__"

class MotoSeguroForm(forms.ModelForm):
    año = forms.ChoiceField(choices=[(x, str(x)) for x in range(2023, 1969, -1)])
    marca = forms.ChoiceField(choices=[("OTRO","OTRO")])
    modelo = forms.CharField(widget=forms.widgets.Select)
    version = forms.CharField(label="Versión", widget=forms.widgets.Select)
    uso = forms.ChoiceField(choices=[
        ("P","Particular"),
        ("C","Comercial"),
    ])
    cero_km = forms.ChoiceField(label="O KM", choices=[("Si","Si"), ("No", "No")])

    def __init__(self, *args, **kwargs):
        super(MotoSeguroForm, self).__init__(*args, **kwargs)
        self.fields['marca'].choices += [(x["marca"],x["marca"]) for x in models.MotoList.objects.all().values("marca").distinct()]
        self.fields['año'].widget.attrs['max'] = datetime.datetime.now().year
        self.initial['uso'] = 'P'
        self.initial["cero_km"] = "No"


    def clean_año(self):
        año = int(self.cleaned_data['año'])
        if año > datetime.datetime.now().year:
            raise forms.ValidationError("El año es invalido")
        return año
    
    def clean_cero_km(self):
        field = self.cleaned_data['cero_km']
        return field == "Si"

    class Meta:
        model = models.MotoSeguro
        fields = "__all__"

class HogarSeguroForm(forms.ModelForm):
    construccion = forms.CharField(label="Tipo de construcción")
    material_techo = forms.CharField(label="Material de Techo")
    m2 = forms.IntegerField(label="Superficie en M2")
    valor = forms.FloatField(label="Valor en pesos")
    rejas = forms.ChoiceField(label="¿Posee Rejas?", 
        choices=[("Si", "Si"), ("No", "No")], 
        initial="Si"
    )
    linderos = forms.ChoiceField(label="Linderos", 
        choices=(
            ("SB","Sin baldio"),
            ("BA","Baldio abandonado"),
            ("BM","Baldio con medianera"),
        ), 
        initial="SB"
    )
    tipo_bici = forms.ChoiceField(label="¿Agrega Bicicleta?", 
        choices=(
            ("NO", "No agrego bicicleta"),
            ("SI", "Si, dentro y fuera del domicilio"),
        ), 
        initial="NO"
    )
    marca_modelo_bici = forms.CharField(label="Marca y Modelo")
    valor_bici = forms.FloatField(label="Valor en pesos")

    class Meta:
        model = models.HogarSeguro
        fields = "__all__"

class ComercioSeguroForm(forms.ModelForm):
    descripcion = forms.CharField(label="Actividad Comercial")
    construccion = forms.CharField(label="Tipo de construcción")
    material_techo = forms.CharField(label="Material de Techo")
    m2 = forms.IntegerField(label="Superficie en M2")
    valor = forms.FloatField(label="Valor en pesos")
    rejas = forms.ChoiceField(label="¿Posee Rejas?", 
        choices=[("Si", "Si"), ("No", "No")], 
        initial="Si"
    )
    linderos = forms.ChoiceField(label="Linderos", 
        choices=(
            ("SB","Sin baldio"),
            ("BA","Baldio abandonado"),
            ("BM","Baldio con medianera"),
        ), 
        initial="SB"
    )

    class Meta:
        model = models.ComercioSeguro
        fields = "__all__"

class BiciSeguroForm(forms.ModelForm):
    marca_modelo = forms.CharField(label="Marca y Modelo")
    año = forms.ChoiceField(choices=[(x, str(x)) for x in range(2023, 2016, -1)])
    tipo = forms.ChoiceField(choices=(
        ("MB","Mountain Bike"),
        ("R","Rutera"),
        ("BMX","BMX"),
        ("P","Paseo"),
    ), initial="MB")
    valor = forms.FloatField(label="Valor en pesos",  min_value=0, initial=0)
    material = forms.ChoiceField(choices=(
        ("AC","Acero"),
        ("AL","Aluminio"),
        ("CA","Carbon"),
        ("TI","Titanio"),
    ), initial="AC")
    rodado = forms.ChoiceField(choices=[(x, str(x)) for x in range(29, 9, -1)])

    def __init__(self, *args, **kwargs):
        super(BiciSeguroForm, self).__init__(*args, **kwargs)
        self.fields['año'].widget.attrs['max'] = datetime.datetime.now().year

    def clean_año(self):
        año = int(self.cleaned_data['año'])
        if año > datetime.datetime.now().year:
            raise forms.ValidationError("El año es invalido")
        return año

    class Meta:
        model = models.BiciSeguro
        fields = "__all__"

class MonopatinSeguroForm(forms.ModelForm):
    año = forms.ChoiceField(choices=[(x, str(x)) for x in range(2023, 2016, -1)])
    marca_modelo = forms.CharField(label="Marca y Modelo")
    tipo = forms.ChoiceField(
        label="Tipo",
        choices=(
            ("B","Bateria"),
            ("E","Electrico"),
        ),
        initial="B"
    )
    valor = forms.FloatField(label="Valor en pesos", min_value=0, initial=0)

    def __init__(self, *args, **kwargs):
        super(MonopatinSeguroForm, self).__init__(*args, **kwargs)
        self.fields['año'].widget.attrs['max'] = datetime.datetime.now().year

    def clean_año(self):
        año = int(self.cleaned_data['año'])
        if año > datetime.datetime.now().year:
            raise forms.ValidationError("El año es invalido")
        return año

    class Meta:
        model = models.MonopatinSeguro
        fields = "__all__"

class CamionSeguroForm(forms.ModelForm):
    año = forms.ChoiceField(choices=[(x, str(x)) for x in range(2023, 1952, -1)])
    año_acoplado = forms.ChoiceField(choices=[(x, str(x)) for x in range(2023, 1952, -1)])
    marca = forms.ChoiceField(choices=[("OTRO","OTRO")])
    modelo = forms.CharField(widget=forms.widgets.Select)
    version = forms.CharField(label="Versión", widget=forms.widgets.Select)
    gnc = forms.ChoiceField(choices=[("Si","Si"), ("No", "No")], initial="No")
    cero_km = forms.ChoiceField(label="O KM", choices=[("Si","Si"), ("No", "No")], initial="No")
    acoplado = forms.ChoiceField(label="¿Agrega acoplado?", choices=[("Si","Si"), ("No", "No")])
    radio = forms.ChoiceField(choices=[
        ("U","Urbano"),
        ("N","Nacional"),
    ])
    marca_modelo_acoplado = forms.CharField(label="Marca y Modelo")
    año_acoplado = forms.ChoiceField(
        label="Año",
        choices=[(x, str(x)) for x in range(2023, 1952, -1)]
    )

    def __init__(self, *args, **kwargs):
        super(CamionSeguroForm, self).__init__(*args, **kwargs)
        self.fields['marca'].choices += [(x["marca"],x["marca"]) for x in models.CamionList.objects.all().values("marca").distinct()]
        self.fields['año'].widget.attrs['max'] = datetime.datetime.now().year
        self.fields['año_acoplado'].widget.attrs['max'] = datetime.datetime.now().year
        self.initial['acoplado'] ="No"


    def clean_año(self):
        año = int(self.cleaned_data['año'])
        if año > datetime.datetime.now().year:
            raise forms.ValidationError("El año es invalido")
        return año
    
    def clean_gnc(self):
        field = self.cleaned_data['gnc']
        return field == "Si"
    
    def clean_cero_km(self):
        field = self.cleaned_data['cero_km']
        return field == "Si"


    def clean_acoplado(self):
        field = self.cleaned_data['acoplado']
        return field == "Si"
    def clean_año_acoplado(self):
        año_acoplado = self.cleaned_data['año_acoplado']
        if año_acoplado > datetime.datetime.now().year:
            raise forms.ValidationError("El año es invalido")
        return año_acoplado

    class Meta:
        model = models.CamionSeguro
        fields = "__all__"

class FlotaSeguroForm(forms.ModelForm):
    class Meta:
        model = models.FlotaSeguro

seguros/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
import uuid
from seguros import forms
from seguros import models

from rest_framework.views import APIView
from rest_framework.response import Response

# Create your views here.

TIPO_FORM_MAP = {
    "auto": forms.AutoSeguroForm,
    "moto": forms.MotoSeguroForm,
    "accidentes": forms.AccidentesSeguroForm,
    "hogar": forms.HogarSeguroForm,
    "comercio": forms.ComercioSeguroForm,
    "bici": forms.BiciSeguroForm,
    "monopatin": forms.MonopatinSeguroForm,
    "camion": forms.CamionSeguroForm,
    "flota": forms.FlotaSeguroForm,
    "vida": forms.VidaSeguroForm,
    "praxis_medica": forms.PraxisMedicaSeguroForm,
    "caucion": forms.CaucionSeguroForm,
    "celular": None,
}

TIPO_MODEL_MAP = {
    "auto": models.AutoList,
    "moto": models.MotoList,
    "camion": models.CamionList,
}

def home(request):
    return redirect(reverse("seguros:tipo-form"))

def terms(request):
    return render(request, "terms.html", {"terms": models.Terms.objects.all().first()})

def privacidad(request):
    return render(request, "privacidad.html", {"privacidad": models.Privacidad.objects.all().first()})

def home(request):
    return redirect(reverse("seguros:tipo-form")+"?tipo=auto")

def tipo_form(request):
    context = {}
    tipo = request.GET.get("tipo", None)
    if not tipo or tipo not in list(TIPO_FORM_MAP.keys()):
        messages.error(request, "Tipo de seguro invalido")
        return redirect("/")

    if tipo == "bici":
        context["tipo"] = tipo
        context["account_form"] = forms.AccountForm
        context["bici_form"] = forms.BiciSeguroForm
        context["monopatin_form"] = forms.MonopatinSeguroForm
    elif tipo == "flota":
        context["tipo"] = tipo
        context["account_form"] = forms.AccountForm
        context["form"] = TIPO_FORM_MAP[tipo]
    else:
        context["tipo"] = tipo
        context["account_form"] = forms.AccountForm
        context["form"] = TIPO_FORM_MAP[tipo]
    return render(request, "seguros/form.html", context)


class GuardarSeguro(APIView):

    def get(self, request, *args, **kwargs):
        if models.UserSeguro.objects.filter(uuid=request.session["uuid"]).exists():
            return render(request, "seguros/account-form.html", {
                "tipo": request.session["tipo"],
                "account_form": forms.AccountForm(),
            })
        else:
            return redirect("/")

    def post(self, request, *args, **kwargs):
        tipo = request.GET.get("tipo", None)
        if not tipo or tipo not in list(TIPO_FORM_MAP.keys()):
            messages.error(request, "Tipo de seguro invalido")
            return redirect("/")

        request.session["tipo"] = tipo
        print(tipo)
        if tipo == "bici":
            tipo_bici = request.POST.get("tipo-bici")
            if tipo_bici in ["bici","monopatin"]:
                form = TIPO_FORM_MAP[tipo_bici]
                form = form(request.POST)
                if form.is_valid():
                    form.save()
            else:
                messages.error(request, "Tipo Bici/Monopatin invalido")
                return redirect("/")
        else:
            form = TIPO_FORM_MAP[tipo]
            print(request.POST)
            form = form(request.POST)
            if not form.is_valid():
                print(form.errors)
                messages.error(request, "Datos de seguro invalidos")
                return redirect("/")

            obj = form.save()
        
        myuuid = uuid.uuid4()
        request.session["uuid"] = str(myuuid)
        user_seguro = models.UserSeguro(
            tipo=tipo,
            uuid=myuuid,
            data_id=int(obj.pk),
            completed=False,
        )
        user_seguro.save()
        return render(request, "seguros/account-form.html", {
            "tipo": tipo,
            "account_form": forms.AccountForm(),
        })
        


def guardar_account(request):
    if request.method == "POST":
        acc_form = forms.AccountForm(request.POST)
        if not acc_form.is_valid():
            messages.error(request, "Datos de cuenta invalidos")
            return redirect("/")
        
        tipo = request.session["tipo"]
        myuuid = request.session["uuid"]
        user_seguro = models.UserSeguro.objects.filter(tipo=tipo, uuid=str(myuuid))
        if not user_seguro.exists():
            messages.error(request, "Datos de seguro no cargados")
            return redirect("/")

        user_seguro = user_seguro.first()
        account = acc_form.save()
        user_seguro.account = account
        user_seguro.completed = True
        user_seguro.save()
        messages.success(request, "Seguro Creado")
        return redirect("/success/?tipo="+str(tipo))

    return redirect("/")


def success(request):
    return render(request, "seguros/success-user.html", {
        "tipo": request.GET.get("tipo", "auto")
    })


class GetModeloByMarca(APIView):

    def get(self, request):
        marca = request.GET.get("marca")
        tipo = request.GET.get("tipo", None)
        if not tipo or tipo not in list(TIPO_FORM_MAP.keys()):
            messages.error(request, "Tipo de seguro invalido")
            return redirect("/")

        model = TIPO_MODEL_MAP[tipo]
        return Response(data={
            "data": model.objects.filter(marca=marca).values("modelo").distinct()
        }, status=200)


class GetVersionesByModelo(APIView):

    def get(self, request):
        modelo = request.GET.get("modelo")
        marca = request.GET.get("marca")
        tipo = request.GET.get("tipo", None)
        if not tipo or tipo not in list(TIPO_FORM_MAP.keys()):
            messages.error(request, "Tipo de seguro invalido")
            return redirect("/")

        model = TIPO_MODEL_MAP[tipo]
        return Response(data={
            "data": model.objects.filter(marca=marca, modelo=modelo).values("version").distinct()
        }, status=200)

seguros/templates/home.html
{% extends "index.html" %}
{% load static %}

{% block main %}
    <h1>AseguraHoy.com</h1>
{% endblock %}

seguros/templates/index.html
{% load static %}
{% load seguros_filters %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" href="{% static 'css/form.css' %}">
        <link rel="stylesheet" href="{% static 'css/links.css' %}">
        <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
        <link rel="stylesheet" href="{% static 'css/helpers.css' %}">
        <link rel="stylesheet" href="{% static 'css/second-page.css' %}">
        <link rel="stylesheet" href="{% static 'css/third-page.css' %}">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Chenla&family=Copse&family=Crete+Round&family=Crimson+Pro:wght@300&family=Crimson+Text:wght@400;600&family=Days+One&family=Inter+Tight:wght@700&family=Poppins:wght@400;600&display=swap" rel="stylesheet">
        {% block css %}
        {% endblock %}
        <title>AseguroHoy.com</title>
        <link rel="shortcut icon" href="{% static 'icons/logo.png' %}" type="image/png">
    </head>
    <body>
        {% include 'include/navbar.html' %}
        <main>
            {% block main %}
            {% endblock %}
            <br>
            <br>
        </main>
        <div class="top-logos">
            
            <span>
                <img src="{% static 'icons/Orbis png.png' %}" alt="orbis">
            </span>
            <span>
                <img style="transform: scale(1.5);" src="{% static 'icons/triunfo pnb.png' %}" alt="triunfo">
            </span>
            <span>
                <img style="transform: scale(1.4);" src="{% static 'icons/Rivadavia png.png' %}" alt="rivadavia">
            </span>
            <span>
                <img src="{% static 'icons/RUS.png' %}" alt="rus">
            </span>
            
        </div>
        <div class="sides second-page">
            <div class="left">
                <div class="top-title">
                    ¿Por qué elegirnos?
                </div>
                <p>
                    Contamos con la más alta tecnología para mantener tu seguro al día.
                </p>
                <p>
                    Recibí tu póliza a tu celular cuando se renueve, de esa manera, nunca tendrás tu documentación vencida.
                </p>
                <p>
                    Asesoramiento y acompañamiento en caso de algún improvisto.
                </p>
                <p>
                    Descuentos especiales en pagos con tarjeta de Crédito, Débito o CBU.
                </p>
                <p>
                    Podes contratar tu póliza para pagos en efectivo mensual en cualquier Rapi Pago, Pago Fácil, Cobro Express, etc.
                </p>
                <br>
            </div>
            <div class="right">
                <div class="top-title">
                    Contrata tu póliza hoy
                </div>
                <div>
                    <div class="list-number">1-Carga tus datos.</div>
                    <div>Completa el formulario de lo que queres asegurar.</div>
                </div>
                <div>
                    <div class="list-number">2-Recibi asesoramiento.</div>
                    <div>
                        Un asesor te brindará una variedad de coberturas
                        para que puedas decidir.
                    </div>
                </div>
                <div>
                    <div class="list-number">3-Contrata online.</div>
                    <div>
                        Se carga el medio de pago con el que deseas
                        abonar y se te brindará tu póliza de seguros.
                    </div>
                </div>
            </div>
        </div>
        <div class="sides third-page">
            <div class="left">
                <div class="top-title">
                    Ventajas de contratar en AseguraHoy
                </div>
                <p>
                    Un Asesor te brindara las mejores opciones para vos y tus bienes, de esa forma, vas a poder informarte y saldar todas tus dudas antes de contratar tu póliza.
                </p>
                <p>
                    Contamos con una linea activa las 24hs para que puedas contactarnos de forma directa y sin necesidad de aguardar en linea.
                </p>
                <p>
                    Contamos con tecnología post venta, priorizando siempre el trato directo con el cliente.
                </p>
            </div>
            <div class="right">
                <div class="top-title">
                    CENTRO DE ATENCIÓN
                </div>
                <div>
                    <div class="list-image">
                        <img src="{% static 'third-page/location.png' %}" alt="direccion">
                    </div>
                    <div>
                        <p>DIRECCIÓN</p>
                        <p>Rivadavia 272 - San Martin, Mendoza.</p>
                    </div>
                </div>
                <div>
                    <div class="list-image">
                        <img src="{% static 'third-page/llamada.png' %}" alt="llamada">
                    </div>
                    <div>
                        <p>TELÉFONO / WHATSAPP</p>
                        <p>2634-32 32 32</p>
                    </div>
                </div>
                <div>
                    <div class="list-image">
                        <img src="{% static 'third-page/reloj.png' %}" alt="reloj">
                    </div>
                    <div>
                        <p>HORARIOS</p>
                        <p>
                            Lunes a Viernes. 09:00 - 20:00<br>
                            Sabado. 09:00 - 13:00
                        </p>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="three-sides">
            <div class="social-side">
                <span>
                    <img src="{% static 'icons/LOGO PNG.png' %}" alt="logo">
                    <img src="{% static 'icons/logotipo.png' %}" alt="logo">
                </span>
                <span>Seguinos en nuestras redes.</span>
                <span>
                    <img src="{% static 'icons/facebook.png' %}" alt="facebook">
                    <img src="{% static 'icons/instagram.png' %}" alt="instagram">
                    <img src="{% static 'icons/whatsapp.png' %}" alt="whatsapp">
                </span>
            </div>
            <div class="info-side">
                AseguraHoy desempeña funciones de productor asesor de seguros conforme a la Ley 22.400, no
                revistiendo el carácter de compañía de seguros y se encuentra registrada con Matrícula 90.161, expedida
                por la Superintendencia de Seguros de la Nación. (<a href="www.ssn.gov.ar">www.ssn.gov.ar</a>)<br><br>
                <a href="www.asegurahoy.com">www.asegurahoy.com</a> es una marca bajo licencia de su titular, Sr. Benjamín Sevilla. Todos los nombres y
                productos mencionados son marcas registradas de su respectivo dueño.
            </div>
            <div class="qr-side">
                <div class="qr">
                    <img src="{% static 'icons/QR.png' %}" alt="QR">
                    <div>
                        <p>Certificado de Aptitud para el Ofrecimiento Público de Contratos de Seguros (CAOPCS)</p>
                        <img src="{% static 'icons/LogoSSN.png' %}" alt="SSN">

                        <div class="bottom-terms">
                            <p>
                                AseguraHoy.com &copy; 2022 <br>
                                Todos los derechos reservados
                            </p>
                            <p>
                                <a href="{% url 'seguros:terms' %}">Términos y Condiciones</a>
                                <a href="{% url 'seguros:privacidad' %}">Privacidad</a>
                            </p>
                        </div>
                    </div>
                   
                </div>
                
            </div>
        </div>
    
    {% block js_scripts %}
    {% endblock %}
    </body>
</html>

seguros/templates/privacidad.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Privacidad</title>
    <link rel="shortcut icon" href="{% static 'icons/logo.png' %}" type="image/png">
</head>
<body>
    <h1>Privacidad</h1>
    <h4>Ultima fecha actualización: {{privacidad.updated|date:"d/M/Y"}}</h4>
    <br>
    {{privacidad.privacidad|safe}}
    <br>
</body>
</html>

seguros/templates/terms.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terminos y Condiciones</title>
</head>
<body>
    <h1>Terminos y Condiciones</h1>
    <h4>Ultima fecha actualización: {{terms.updated|date:"d/M/Y"}}</h4>
    <br>
    {{terms.terms|safe}}
    <br>
</body>
</html>